package com.example.android.tourguideapp;

import android.content.Context;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;

public class PlaceData {

    public static ArrayList<Place> getPlacesList(Context context) {

        ArrayList<Place> places = new ArrayList<Place>();
        places.add(new Place(context.getString(R.string.york_minster_name), context.getString(R.string.york_minster_description), context.getString(R.string.york_minster_address), context.getString(R.string.york_minster_hours), context.getString(R.string.york_minster_phone), context.getString(R.string.york_minster_web), 53.962329, -1.081975, Place.POPULARS, R.drawable.york_minster));
        places.add(new Place(context.getString(R.string.mansion_house_name), context.getString(R.string.mansion_house_description), context.getString(R.string.mansion_house_address), context.getString(R.string.mansion_house_hours), context.getString(R.string.mansion_house_phone), context.getString(R.string.mansion_house_web), 53.959946, -1.084753, Place.POPULARS, R.drawable.mansionhouse));
        places.add(new Place(context.getString(R.string.shambles_market_name), context.getString(R.string.shambles_market_description), context.getString(R.string.shambles_market_address), context.getString(R.string.shambles_market_hours), context.getString(R.string.shambles_market_phone), context.getString(R.string.shambles_market_web), 53.959260, -1.080447, Place.POPULARS, R.drawable.shambles_market));
        places.add(new Place(context.getString(R.string.jorvik_viking_centre_name), context.getString(R.string.jorvik_viking_centre_description), context.getString(R.string.jorvik_viking_centre_address), context.getString(R.string.jorvik_viking_centre_hours), context.getString(R.string.jorvik_viking_centre_phone), context.getString(R.string.jorvik_viking_centre_web), 53.957409, -1.080301, Place.MUSEUMS, R.drawable.jorvik));
        places.add(new Place(context.getString(R.string.york_castle_name), context.getString(R.string.york_castle_description), context.getString(R.string.york_castle_address), context.getString(R.string.york_castle_hours), context.getString(R.string.york_castle_phone), context.getString(R.string.york_castle_web), 53.955821, -1.079940, Place.POPULARS, R.drawable.york_castle));
        places.add(new Place(context.getString(R.string.york_castle_museum_name), context.getString(R.string.york_castle_museum_description), context.getString(R.string.york_castle_museum_address), context.getString(R.string.york_castle_museum_hours), context.getString(R.string.york_castle_museum_phone), context.getString(R.string.york_castle_museum_web), 53.955609, -1.078291, Place.MUSEUMS, R.drawable.york_castle_museum));
        places.add(new Place(context.getString(R.string.york_museum_gardens_name), context.getString(R.string.york_museum_gardens_description), context.getString(R.string.york_museum_gardens_address), context.getString(R.string.york_museum_gardens_phone), context.getString(R.string.york_museum_gardens_web), 53.961469, -1.088318, Place.POPULARS, R.drawable.york_gardens));
        places.add(new Place(context.getString(R.string.york_dungeon_name), context.getString(R.string.york_dungeon_description), context.getString(R.string.york_dungeon_address), context.getString(R.string.york_dungeon_hours), context.getString(R.string.york_dungeon_phone), context.getString(R.string.york_dungeon_web), 53.956818, -1.081913, Place.POPULARS, R.drawable.york_dungeon));
        places.add(new Place(context.getString(R.string.yorkshire_air_museum_name), context.getString(R.string.yorkshire_air_museum_description), context.getString(R.string.yorkshire_air_museum_address), context.getString(R.string.yorkshire_air_museum_hours), context.getString(R.string.yorkshire_air_museum_phone), context.getString(R.string.yorkshire_air_museum_web), 53.925371, -0.965686, Place.MUSEUMS, R.drawable.yorkshire_air_museum));
        places.add(new Place(context.getString(R.string.york_chocolate_story_name), context.getString(R.string.york_chocolate_story_description), context.getString(R.string.york_chocolate_story_address), context.getString(R.string.york_chocolate_story_hours), context.getString(R.string.york_chocolate_story_phone), context.getString(R.string.york_chocolate_story_web), 53.960031, -1.080413, Place.MUSEUMS, R.drawable.york_chocolate_story));
        places.add(new Place(context.getString(R.string.national_railway_museum_name), context.getString(R.string.national_railway_museum_description), context.getString(R.string.national_railway_museum_address), context.getString(R.string.national_railway_museum_hours), context.getString(R.string.national_railway_museum_phone), context.getString(R.string.national_railway_museum_web), 53.960548, -1.096367, Place.MUSEUMS, R.drawable.york_railway_museum));
        places.add(new Place(context.getString(R.string.yorkshire_museum_name), context.getString(R.string.yorkshire_museum_description), context.getString(R.string.yorkshire_museum_address), context.getString(R.string.yorkshire_museum_hours), context.getString(R.string.yorkshire_museum_phone), context.getString(R.string.yorkshire_museum_web), 53.961941, -1.087360, Place.MUSEUMS, R.drawable.yorkshire_museum));
        places.add(new Place(context.getString(R.string.the_shambles_name), context.getString(R.string.the_shambles_description), context.getString(R.string.the_shambles_address), context.getString(R.string.the_shambles_phone), context.getString(R.string.the_shambles_web), 53.959389, -1.080077, Place.POPULARS, R.drawable.the_shambles));
        places.add(new Place(context.getString(R.string.pivni_york_name), context.getString(R.string.pivni_york_description), context.getString(R.string.pivni_york_address), context.getString(R.string.pivni_york_hours), context.getString(R.string.pivni_york_phone), context.getString(R.string.pivni_york_web), 53.959740, -1.080812, Place.PUBS, R.drawable.pivni));
        places.add(new Place(context.getString(R.string.golden_fleece_name), context.getString(R.string.golden_fleece_description), context.getString(R.string.golden_fleece_address), context.getString(R.string.golden_fleece_hours), context.getString(R.string.golden_fleece_phone), context.getString(R.string.golden_fleece_web), 53.958701, -1.079643, Place.PUBS, R.drawable.golden_fleece));
        places.add(new Place(context.getString(R.string.barbakan_restaurant_name), context.getString(R.string.barbakan_restaurant_description), context.getString(R.string.barbakan_restaurant_address), context.getString(R.string.barbakan_restaurant_hours), context.getString(R.string.barbakan_restaurant_phone), context.getString(R.string.barbakan_restaurant_web), 53.956918, -1.075758, Place.PUBS, R.drawable.barbakan));
        places.add(new Place(context.getString(R.string.rustique_name), context.getString(R.string.rustique_description), context.getString(R.string.rustique_address), context.getString(R.string.rustique_hours), context.getString(R.string.rustique_phone), context.getString(R.string.rustique_web), 53.956930, -1.080644, Place.PUBS, R.drawable.rustique));
        places.add(new Place(context.getString(R.string.grand_hotel_name), context.getString(R.string.grand_hotel_description), context.getString(R.string.grand_hotel_address), context.getString(R.string.grand_hotel_phone), context.getString(R.string.grand_hotel_web), 53.958551, -1.089047, Place.HOTELS, R.drawable.grand_hotel));
        places.add(new Place(context.getString(R.string.grays_court_hotel_name), context.getString(R.string.grays_court_hotel_description), context.getString(R.string.grays_court_hotel_address), context.getString(R.string.grays_court_hotel_phone), context.getString(R.string.grays_court_hotel_web), 53.962938, -1.080346, Place.HOTELS, R.drawable.grays_court));
        places.add(new Place(context.getString(R.string.hilton_york_name), context.getString(R.string.hilton_york_description), context.getString(R.string.hilton_york_address), context.getString(R.string.hilton_york_phone), context.getString(R.string.hilton_york_web), 53.956371, -1.080541, Place.HOTELS, R.drawable.hilton));

        long seed = System.nanoTime();
        Collections.shuffle(places, new Random(seed));

        return places;
    }
}
